name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3', '3.4']
        rails-version: ['rails-7.1', 'rails-7.2', 'rails-8.0']
        exclude:
          # Rails 8 requires Ruby 3.2+
          - ruby-version: '3.1'
            rails-version: 'rails-8.0'

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Run Standard (linting)
      run: bundle exec rake standard
    
    - name: Run RSpec (tests)
      run: bundle exec rake spec
